openapi: "3.0.1"
info:
  version: 0.0.1
  title: Kakapo API
  description: OpenAPI Spec for https://kakaposocial.com/
servers:
  - url: http://localhost:8080/api/v1/
tags:
  - name: Authentication
paths:
  /token/authenticate:
    $ref: "./routes/token.yaml#/paths/authenticate"
  /token/refresh:
    $ref: "./routes/token.yaml#/paths/refresh"
