openapi: "3.1.0"

info:
  version: 1.0.0
  title: Kakapo API
  description: OpenAPI Spec for Kakapo Social.
  x-logo:
    url: https://raw.githubusercontent.com/James11T/kakapo/main/ui/public/banner_with_spacing.png
    altText: Kakapo Social
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

security:
  - authorizationToken: []

servers:
  - url: http://localhost:8080/api/v1
    description: Local Test Deployment.
  - url: https://kakaposocial.com/api/v1
    description: Production Deployment.
  - url: https://beta.kakaposocial.com/api/v1
    description: Pre Production Deployment.

tags:
  - name: authentication
    description: Contains all endpoints for managing authentication through the use of tokens.
    x-displayName: Authentication
  - name: users
    description: Contains all endpoints for fetching, creating and updating users.
    x-displayName: Users
  - name: system
    description: Contains all endpoints for interacting with and reading information from the system.
    x-displayName: System
  - name: placeholder
    description: Contains all endpoints that are not yet documented or implemented.
    x-displayName: placeholder
  - name: status
    description: Contains all endpoints for checking the status of the API.
    x-displayName: Status
  - name: tokens
    description: Contains all endpoints that generate, process and manage tokens.
    x-displayName: Tokens
  - name: user-details
    description: Contains all endpoints that are for managing User instances.
    x-displayName: User Details
  - name: friendships
    description: Contains all endpoints that are for managing user friendships.
    x-displayName: Friendships
  - name: friend-requests
    description: Contains all endpoints that are for managing and sending friend requests.
    x-displayName: Friend Requests
  - name: mfa
    description: Contains all endpoints that are for managing multi-factor authentication.
    x-displayName: MFA
  - name: passwords
    description: Contains all endpoints that are for managing passwords.
    x-displayName: Passwords
  - name: posts
    description: Contains all endpoints that are for managing posts.
    x-displayName: Posts
  - name: post-details
    description: Contains all endpoints that are for managing details of posts.
    x-displayName: Post Details
  - name: comments
    description: Contains all endpoints that are for managing comments on posts.
    x-displayName: Comments
x-tagGroups:
  - name: System
    tags:
      - status
  - name: Authentication
    tags:
      - tokens
      - mfa
      - passwords
  - name: Users
    tags:
      - user-details
      - friendships
      - friend-requests
  - name: Posts
    tags:
      - post-details
      - comments

paths:
  /status:
    $ref: "./routes/status.yaml#/status"
  /tokens/authenticate:
    $ref: "./routes/tokens.yaml#/authenticate"
  /tokens/refresh:
    $ref: "./routes/tokens.yaml#/refresh"
  /users:
    $ref: "./routes/users.yaml#/users"
  /users/{username}:
    $ref: "./routes/users.yaml#/user"
  /users/{username}/is-available:
    $ref: "./routes/users.yaml#/is-username-available"
  /users/{username}/friends:
    $ref: "./routes/friends.yaml#/friends"
  /users/{username}/friends/{friendUsername}:
    $ref: "./routes/friends.yaml#/removeFriend"
  /users/{username}/friend-requests:
    $ref: "./routes/friendRequests.yaml#/friend-requests"
  /auth/mfa:
    $ref: "./routes/mfa.yaml#/mfa"
  /auth/request-password-reset:
    $ref: "./routes/auth.yaml#/request-password-reset"
  /auth/reset-password:
    $ref: "./routes/auth.yaml#/reset-password"
  /auth/whoami:
    $ref: "./routes/auth.yaml#/whoami"
  /posts:
    $ref: "./routes/posts.yaml#/posts"
  /posts/{postId}:
    $ref: "./routes/posts.yaml#/post"
  /posts/{postId}/likes:
    $ref: "./routes/posts.yaml#/likes"
  /posts/{postId}/comments:
    $ref: "./routes/comments.yaml#/comments"
  /posts/{postId}/comments/{commentId}:
    $ref: "./routes/comments.yaml#/comment"
  /posts/{postId}/comments/{commentId}/likes:
    $ref: "./routes/comments.yaml#/comment-likes"

components:
  securitySchemes:
    authorizationToken:
      type: apiKey
      name: Authorization
      in: header
      x-displayName: Authorization Token
