openapi: 3.1.0
info:
  version: 1.0.0
  title: Kakapo API
  description: OpenAPI Spec for Kakapo Social.
  x-logo:
    url: >-
      https://raw.githubusercontent.com/James11T/kakapo/main/ui/public/banner_with_spacing.png
    altText: Kakapo Social
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
security:
  - authorizationToken: []
servers:
  - url: http://localhost:5000/api/v1
    description: Local Test Deployment.
  - url: https://kakaposocial.com/api/v1
    description: Production Deployment.
  - url: https://beta.kakaposocial.com/api/v1
    description: Pre Production Deployment.
tags:
  - name: authentication
    description: Endpoints for managing authentication through the use of tokens.
    x-displayName: Authentication
  - name: users
    description: Endpoints for fetching, creating and updating users.
    x-displayName: Users
  - name: system
    description: Endpoints for interacting with and reading information from the system.
    x-displayName: System
  - name: placeholder
    description: Endpoints that are not yet documented or implemented.
    x-displayName: placeholder
  - name: status
    description: Endpoints for checking the status of the API.
    x-displayName: Status
  - name: tokens
    description: Endpoints that generate, process and manage tokens.
    x-displayName: Tokens
  - name: user-details
    description: Endpoints that are for managing User instances.
    x-displayName: User Details
  - name: friendships
    description: Endpoints that are for managing user friendships.
    x-displayName: Friendships
  - name: friend-requests
    description: Endpoints that are for managing and sending friend requests.
    x-displayName: Friend Requests
  - name: mfa
    description: Endpoints that are for managing multi-factor authentication.
    x-displayName: MFA
  - name: passwords
    description: Endpoints that are for managing passwords.
    x-displayName: Passwords
  - name: posts
    description: Endpoints that are for managing posts.
    x-displayName: Posts
  - name: post-details
    description: Endpoints that are for managing details of posts.
    x-displayName: Post Details
  - name: comments
    description: Endpoints that are for managing comments on posts.
    x-displayName: Comments
x-tagGroups:
  - name: System
    tags:
      - status
  - name: Authentication
    tags:
      - tokens
      - mfa
      - passwords
  - name: Users
    tags:
      - user-details
      - friendships
      - friend-requests
  - name: Posts
    tags:
      - post-details
      - comments
paths:
  /status:
    $ref: paths/status.yaml
  /tokens/authenticate:
    $ref: paths/tokens_authenticate.yaml
  /tokens/refresh:
    $ref: paths/tokens_refresh.yaml
  /users:
    $ref: paths/users.yaml
  /users/{username}:
    $ref: paths/users_{username}.yaml
  /users/{username}/is-available:
    $ref: paths/users_{username}_is-available.yaml
  /users/{username}/friends:
    $ref: paths/users_{username}_friends.yaml
  /users/{username}/friends/{friendUsername}:
    $ref: paths/users_{username}_friends_{friendUsername}.yaml
  /users/{username}/friend-requests:
    $ref: paths/users_{username}_friend-requests.yaml
  /auth/mfa:
    $ref: paths/auth_mfa.yaml
  /auth/mfa/{mfaId}:
    $ref: paths/auth_mfa_{mfaId}.yaml
  /auth/request-password-reset:
    $ref: paths/auth_request-password-reset.yaml
  /auth/reset-password:
    $ref: paths/auth_reset-password.yaml
  /auth/whoami:
    $ref: paths/auth_whoami.yaml
  /posts:
    $ref: paths/posts.yaml
  /posts/{postId}:
    $ref: paths/posts_{postId}.yaml
  /posts/{postId}/likes:
    $ref: paths/posts_{postId}_likes.yaml
  /posts/{postId}/comments:
    $ref: paths/posts_{postId}_comments.yaml
  /posts/{postId}/comments/{commentId}:
    $ref: paths/posts_{postId}_comments_{commentId}.yaml
  /posts/{postId}/comments/{commentId}/likes:
    $ref: paths/posts_{postId}_comments_{commentId}_likes.yaml
components:
  securitySchemes:
    authorizationToken:
      type: apiKey
      name: Authorization
      in: header
      x-displayName: Authorization Token
