apis:
  kakapo@1.0.0:
    root: ./openapi.yaml

extends:
  - recommended

rules:
  operation-2xx-response:
    severity: off
  operation-4xx-response:
    severity: off

theme:
  openapi:
    htmlTemplate: ./docs/index.html
    theme:
      colors:
        primary:
          main: "#82ad5a"
    hideDownloadButton: true
